"""
Phase 11 – Publishing Pack Generator
--------------------------------------
Generates all distribution assets needed for YouTube / TikTok / Reels upload:
  - SEO-optimised title variants (5)
  - Keyword-rich description (1800 chars)
  - 30 hashtags (trending + topic-specific)
  - Chapter markers (for 16:9 long-form)
  - Thumbnail prompt (for Stable Diffusion / Gemini Imagen generation)
  - Upload checklist JSON

Inputs come from the existing `distribution_meta.json` and `qc_report.json`
generated by `distribution.py` and `qc_auditor.py`.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


class PublishingPackGenerator:
    """Generates the complete metadata pack for platform upload."""

    SHORTS_PLATFORMS = ["YouTube Shorts", "TikTok", "Instagram Reels"]
    LONGFORM_PLATFORM = "YouTube (Long-form Documentary)"

    def generate(
        self,
        run_dir: Path,
        topic: str,
        script_data: Optional[dict] = None,
        qc_results: Optional[dict] = None,
        output_path: Optional[Path] = None,
    ) -> dict:
        run_dir = Path(run_dir)
        if output_path is None:
            output_path = run_dir / "publishing_pack.json"

        # Load existing distribution meta if present
        dist_meta: dict = {}
        dist_path = run_dir / "distribution_meta.json"
        if dist_path.exists():
            try:
                dist_meta = json.loads(dist_path.read_text(encoding="utf-8"))
            except Exception:
                pass

        # Load QC report if not passed in
        if qc_results is None:
            qc_path = run_dir / "qc_report.json"
            if qc_path.exists():
                try:
                    qc_results = json.loads(qc_path.read_text(encoding="utf-8"))
                except Exception:
                    qc_results = {}
            else:
                qc_results = {}

        existing_titles = dist_meta.get("titles", [])
        existing_desc = dist_meta.get("description", "")

        titles = self._build_titles(topic, existing_titles)
        description = self._build_description(topic, existing_desc, qc_results)
        hashtags = self._build_hashtags(topic)
        chapter_markers = self._build_chapter_markers(script_data)
        thumbnail_prompt = self._build_thumbnail_prompt(topic)
        checklist = self._build_checklist(run_dir, qc_results)

        primary_title = titles[0] if titles else f"The {topic.title()} Mystery"
        shorts_title = f"{topic.title()}: The Truth They Hid #Shorts"[:100]
        shorts_description = (
            f"Unsealed evidence from the {topic} investigation. "
            f"Subscribe to Unsealed Files for full documentary breakdowns. #shorts #mystery"
        )

        pack = {
            "generated_at": datetime.now(timezone.utc).isoformat() + "Z",
            "topic": topic,
            "title": primary_title,
            "titles": titles,
            "description": description,
            "tags": hashtags,
            "hashtags": hashtags,
            "chapters": chapter_markers,
            "chapter_markers": chapter_markers,
            "thumbnail_prompt": thumbnail_prompt,
            "shorts_title": shorts_title,
            "shorts_description": shorts_description,
            "upload_checklist": checklist,
            "platform_long_form": self.LONGFORM_PLATFORM,
            "platforms_short_form": self.SHORTS_PLATFORMS,
        }

        output_path.write_text(json.dumps(pack, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"[PublishingPack] Generated: {output_path.name}")
        self._print_summary(pack)
        return pack

    # ------------------------------------------------------------------
    # Builders
    # ------------------------------------------------------------------

    def _build_titles(self, topic: str, existing: list) -> list:
        slug = topic.strip().title()
        generated = [
            f"The {slug} Mystery: What They Don't Want You to Know",
            f"CLASSIFIED: The Truth Behind {slug} | Full Documentary",
            f"The {slug} Cover-Up That Changed Everything",
            f"Unsealed Files: {slug} | The Evidence They Buried",
            f"[EXPOSED] {slug}: The Documentary That Asks Forbidden Questions",
        ]
        # Deduplicate, put existing first
        seen = set()
        titles = []
        for t in (existing + generated):
            if t not in seen:
                seen.add(t)
                titles.append(t)
        return titles[:5]

    def _build_description(self, topic: str, existing: str, qc_results: dict) -> str:
        if existing and len(existing) > 400:
            return existing[:1800]
        score = qc_results.get("hook_audit", {}).get("score", 85)
        return (
            f"In this documentary we investigate {topic} — the anomalies, "
            f"the classified records, and the evidence that mainstream media "
            f"refuses to cover. Every fact is sourced, every claim is verified. "
            f"This is not speculation. This is the unsealed record.\n\n"
            f"Retention Score: {score}/100 | Verified Claims | No Stock Filler\n\n"
            f"SUBSCRIBE to Unsealed Files for weekly classified investigations.\n"
            f"LIKE this video to help surface it to independent researchers.\n\n"
            f"#documentary #{re.sub(r'[^a-z0-9]', '', topic.lower())} "
            f"#unsealed #classified #truedocumentary"
        )[:1800]

    def _build_hashtags(self, topic: str) -> list:
        topic_tag = re.sub(r"[^a-z0-9]", "", topic.lower())
        base = [
            "documentary", "classified", "unsealed", "history", "mystery",
            "conspiracy", "truths", "exposed", "investigation", "evidence",
            "shorts", "youtubeshorts", "viral", "mindblowing", "exclusive",
            "coverup", "secretfiles", "declassified", "hidden", "forbidden",
        ]
        specific = [
            topic_tag,
            topic_tag + "mystery",
            topic_tag + "classified",
            topic_tag + "documentary",
            topic_tag + "truth",
            topic_tag + "facts",
            topic_tag + "secrets",
            topic_tag + "revealed",
            topic_tag + "exposed",
            "unsealed" + topic_tag,
        ]
        all_tags = ["#" + t for t in base] + ["#" + t for t in specific]
        return list(dict.fromkeys(all_tags))[:30]  # deduplicated, cap at 30

    def _build_chapter_markers(self, script_data: Optional[dict]) -> list:
        if not script_data:
            return [
                {"time": "0:00", "label": "Cold Hook", "title": "Cold Hook"},
                {"time": "0:45", "label": "The Evidence", "title": "The Evidence"},
                {"time": "2:00", "label": "The Cover-Up", "title": "The Cover-Up"},
                {"time": "3:30", "label": "The Revelation", "title": "The Revelation"},
                {"time": "4:45", "label": "The Verdict", "title": "The Verdict"},
            ]
        markers = []
        elapsed = 0.0
        if script_data.get("acts"):
            for act in script_data.get("acts", []):
                act_title = act.get("act_title", f"Part {act.get('act_number', 1)}")
                mins = int(elapsed // 60)
                secs = int(elapsed % 60)
                markers.append({"time": f"{mins}:{secs:02d}", "label": act_title, "title": act_title})
                # Estimate act duration from scene count (~15s per scene)
                elapsed += len(act.get("scenes", [])) * 15
        elif script_data.get("scenes"):
            for idx, sc in enumerate(script_data.get("scenes", [])):
                sc_type = sc.get("scene_type", "").upper()
                sc_text = sc.get("narration_text") or sc.get("narration") or f"Scene {idx+1}"
                label = f"{sc_type}: {sc_text[:30].strip()}" if sc_type else sc_text[:35].strip()
                mins = int(elapsed // 60)
                secs = int(elapsed % 60)
                markers.append({"time": f"{mins}:{secs:02d}", "label": label, "title": label})
                elapsed += float(sc.get("duration", 10.0))

        if not markers:
            markers = [{"time": "0:00", "label": "Cold Hook", "title": "Cold Hook"}]
        return markers

    def _build_thumbnail_prompt(self, topic: str) -> str:
        return (
            f"Cinematic documentary thumbnail for topic '{topic}'. "
            f"Style: dramatic red/gold color grade, classified document aesthetic, "
            f"1920x1080 16:9, photorealistic, text overlay 'CLASSIFIED' in bold white font "
            f"with red 'UNSEALED' stamp, 35mm film grain, dark vignette, high contrast. "
            f"Content: central dramatic visual of {topic} with government document background."
        )

    def _build_checklist(self, run_dir: Path, qc_results: dict) -> dict:
        status = qc_results.get("status", "UNKNOWN")
        score = qc_results.get("hook_audit", {}).get("score", 0)

        def exists(name: str) -> bool:
            return (run_dir / name).exists()

        return {
            "qc_status": status,
            "retention_score": score,
            "ready_to_upload": status in ("PASSED", "PASS", "WARNING"),
            "files": {
                "final_video": exists("06_final_render.mp4"),
                "license_manifest": exists("license_manifest.json"),
                "qc_report": exists("qc_report.json"),
                "captions_ass": exists("03_captions.ass"),
                "shorts_dir": (run_dir / "shorts").exists(),
                "publishing_pack": True,  # this file being written now
            },
            "upload_notes": [
                "Set end screen 'Subscribe' card at 0:45 before end",
                "Upload .ass captions to YouTube for auto-caption override",
                "Schedule publish for peak hour (18:00-20:00 local)",
                "Pin first comment with chapter markers",
                "Add to 'Unsealed Files' playlist",
            ],
        }

    def _print_summary(self, pack: dict) -> None:
        print("\n[PublishingPack] ===== UPLOAD READY CHECKLIST =====")
        print(f"  Topic       : {pack['topic']}")
        print(f"  Best Title  : {pack['titles'][0]}")
        print(f"  Hashtags    : {len(pack['hashtags'])} tags")
        print(f"  Chapters    : {len(pack['chapter_markers'])} markers")
        print(f"  QC Status   : {pack['upload_checklist']['qc_status']}")
        ready = pack["upload_checklist"]["ready_to_upload"]
        print(f"  Ready?      : {'YES - Upload approved' if ready else 'NO - Fix QC issues first'}")
        print("=" * 48)
